### ISSUE TITLE
Can't see clipboard in combination with other library

### ISSUE THREAD

**Issue by lenskikh** [spyoungtech/pyperclip3#24]
```
keyboard.press_and_release('ctrl+a')
keyboard.send('ctrl+c')
pyclip.paste(text=True)
```
If I open notepad and click ctrl+v I'll see the text. But pyclip does not see.

**Comment by spyoungtech** [comment]
Sorry, can't reproduce using notepad. Seems to work for me.

![image](https://user-images.githubusercontent.com/15212758/205540344-c4d048b6-dd59-438f-81e6-93fe75e8dfe1.png)

**Comment by spyoungtech** [comment]
I take it back. I was able to reproduce it, but intermittently. The reason for this is that the application takes some time to receive the keystrokes and change the clipboard. If you add a small sleep between `send('ctrl+c')` and `pyclip.paste(text=True)` this becomes 100% reliable.

```python
keyboard.press_and_release('ctrl+a')
keyboard.send('ctrl+c')
time.sleep(0.1)
pyclip.paste(text=True)
```

So, in essence, the problem is you're accessing the clipboard before the contents actually change.
